### ISSUE TITLE
Rekindle collaboration?

### ISSUE THREAD

**Issue by bherila** [braxex/mui-phone-input-ssr#10]
I have been added as a collaborator to https://github.com/alexplumb/material-ui-phone-number/

I think you might as well retain this package since you appear to be working on it and can maintain your deployment agility with your own npm package etc.. But, do you have interest in syncing up again from time to time?

-Ben

**Comment by braxex** [comment]
Hi Ben - Glad to hear it. I'm happy to help in any way I can, whether that means working all together on `material-ui-phone-number` or maintaining the two separate repos and syncing up frequently. From my standpoint I think either could work, as the only real changes that differentiate this repo are currently SSR and TS support. Thoughts?

**Comment by bherila** [comment]
My suggestion would be  for us to sync up as much as possible, I don't want you to lose your forks and I don't think the sync process will be too arduous as long as we align on major changes :D

I'm also open to converting all the js to ts/tsx as long as @alexplumb  is ok with it? Will open an issue there,

**Comment by braxex** [comment]
Hey @bherila and @alexplumb. Apologies for the lack in communication the past few weeks, as I've been a bit busy. As stated above, I'm open to coordinating, but the more I think about it, I think it might be more beneficial to users of both packages to combine the work from `mui-phone-input-ssr` (SSR-support, TS, formatting changes) into `material-ui-phone-number`. Would you both be open to that? I would also be happy to join as a maintainer of `material-ui-phone-number` and lend a hand to the ongoing work there. Thoughts?

**Comment by bherila** [comment]
Hi @braxex I am definitely open to it and encouraging! However I don't have permissions on the underlying npm package so we'll need @alexplumb  to help with release

I'm a bit underwater at work this week but will take a look at the open PRs this weekend!

**Comment by alexplumb** [comment]
Happy to have it all merged into one (and for the codebase to be updated to ts)

**Comment by braxex** [comment]
@alexplumb Sounds great. I'll plan on directing users of this repo back to `material-ui-phone-number`. Would you be willing to add me as a collaborator? I'd be happy to lend a hand with issues and future updates.
