### ISSUE TITLE
inputRef is shadowed by spread

### ISSUE THREAD

**Issue by balzdur** [braxex/mui-phone-input-ssr#12]
There is an issue regarding `inputRef`:

- in the source code, you intercept this value in order to use it internaly
- in the `render` method, spreading the rest of the props shadow the previously set `inputRef` value

```ts
<TextField
        placeholder={statePlaceholder}
        value={formattedNumber}
        className={inputClass}
        inputRef={this.handleRefInput} // this value will be replaced by the value from restProps
        error={error || !this.checkIfValid()}
        onChange={this.handleInput}
        onClick={this.handleInputClick}
        onFocus={this.handleInputFocus}
        onBlur={this.handleInputBlur}
        onKeyDown={this.handleInputKeyDown}
        type="tel"
        InputProps={{
          ...dropdownProps,
          ...InputProps,
        }}
        {...restProps}
      />
```

An easy fix is to remove `inputRef` from `...restProps`.

**Comment by braxex** [comment]
Hi @balzdur, thanks for opening this issue. We're currently working on potentially merging this repo with https://github.com/alexplumb/material-ui-phone-number, but this seems like a good change. Will you submit a PR?
