### ISSUE TITLE
Issue formatting some countries

### ISSUE THREAD

**Issue by sarahhublo** [braxex/mui-phone-input-ssr#5]
Hi, 
Thank you for the work on library. Very useful.
We have some issues with autoformat. We need the following format
Italy ⇒  +39 XXX XXX XXX or +39 XXX XXX XXXX not +39 XXX XXXXXXX
Luxembourg ⇒  +35 2 XXX XXX XXX
Netherlands ⇒  +31 6 XXXXXXXX not +31 XX XXXXXXXX

We tried to set autoFormat to false, and set a value with our format, but input deletes the spaces anyway.

**Comment by braxex** [comment]
Hi @sarahhublo,
Thanks for submitting this issue. I've deployed an update for [v1.2.1](https://www.npmjs.com/package/mui-phone-input-ssr/v/1.2.1) that should address it for you ([related PR](https://github.com/braxex/mui-phone-input-ssr/pull/7)). Would you please confirm and close the issue if we're good to go?
Thanks!

**Comment by sarahhublo** [comment]
Hi @braxex !
Thank you so much for the fast reply and action ! 
I looked into your PR, looks good to me except for Netherlands I am not sure about changing dialing code from +31 to +316 => because the right dialing code is +31 for this country. I would say : let the +31, and change only the format => 
`[
    'Netherlands',
    ['europe', 'european-union'],
    'nl',
    '31',
    '+.. . ........',
  ]`
  
But it is weird, because I upgraded the lib and I tested with the latest version 1.2.1 (italy and Luxembourg) , the behaviour didn't change, still the old behaviour. Any idea ?

**Comment by braxex** [comment]
Hi @sarahhublo. Apologies for the miscue. It was a minor build issue on my end, but it's now resolved and I've deployed [v1.2.3](https://www.npmjs.com/package/mui-phone-input-ssr/v/1.2.3), which should have the formatting you're expecting.

**Comment by sarahhublo** [comment]
Hi again @braxex ! Works great now ! Thank you so much for your help
